sudo: required
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.18.0

matrix:
  include:
    - language: node_js
      install: true
      script:
        - cd web
        - sudo docker build -t web .
        - sudo docker tag web asempc/wevote:travis-web
    - language: cpp
      install:
        - sudo rm /usr/local/bin/docker-compose
        - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
        - sudo chmod +x docker-compose
        - sudo mv docker-compose /usr/local/bin
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - sudo apt-get update
        - sudo apt-get -y install docker-ce
      script:
        - sudo docker-compose up --build
