version: '3.4'
services:
  computational:
    image: asempc/wevote:computational-basic
    ports:
      - target: 34568
        published: 34568
        protocol: tcp
    stdin_open: true
    tty: true

  database:
    image: mongo
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"

  web:
    image: asempc/wevote:web
    ports:
      - 3000:3000
    links:
      - computational
      - database

    depends_on:
      - database 
      - computational

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - computational
    command: computational:34568
