version: "2"
services:
  web:
    image: asempc/wevote:web
    ports:
      - "3000:3000"
    links:
      - database
      - computational
    depends_on:
      - database # To make sure this sevice is run before web app
      - computational

  computational:
    image: asempc/wevote:computational-basic
    ports:
      - "34568:34568"
  
  database:
    image: mongo
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"

