version: '3.4'
services:
  computational:
    build: .
    ports:
      - target: "34568"
        published: "34568"
        protocol: tcp
    stdin_open: true
    tty: true
    network_mode: "host"

  database:
    image: mongo
    network_mode: "host"
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"

  web:
    build: ./web
    ports:
      - 3000:3000
    network_mode: "host"
    depends_on:
      - database 
      - computational
