version: '3.4'
services:
  database:
    image: mongo
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"
    network_mode: "host"
  web:
    build: .
    ports:
      - 3000:3000
    network_mode: "host"
    depends_on:
      - database 
